// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/parkhub/api/internal/config"
	"github.com/parkhub/api/internal/handler"
	"github.com/parkhub/api/internal/repository/impl"
	"github.com/parkhub/api/internal/router"
	impl2 "github.com/parkhub/api/internal/service/impl"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeApp wires all dependencies and returns a configured Router.
// Call r.Setup() then r.GetEngine() to start serving.
func InitializeApp(cfg *config.Config, db *gorm.DB) (*router.Router, error) {
	engine := NewGinEngine(cfg)
	jwtManager := NewJWTManager(cfg)
	userRepo := impl.NewUserRepo(db)
	tenantRepo := impl.NewTenantRepo(db)
	refreshTokenRepo := impl.NewRefreshTokenRepo(db)
	smsCodeRepo := impl.NewSmsCodeRepo(db)
	loginLogRepo := impl.NewLoginLogRepo(db)
	authService := impl2.NewAuthService(userRepo, tenantRepo, refreshTokenRepo, smsCodeRepo, loginLogRepo, jwtManager)
	authHandler := handler.NewAuthHandler(authService)
	tenantService := impl2.NewTenantService(tenantRepo)
	tenantHandler := handler.NewTenantHandler(tenantService)
	auditLogRepo := impl.NewAuditLogRepo(db)
	auditLogService := impl2.NewAuditLogService(auditLogRepo)
	userService := impl2.NewUserService(userRepo, tenantRepo, loginLogRepo, auditLogService)
	userHandler := handler.NewUserHandler(userService, auditLogService)
	parkingLotRepo := impl.NewParkingLotRepo(db)
	billingRuleRepo := impl.NewBillingRuleRepo(db)
	parkingLotService := impl2.NewParkingLotService(parkingLotRepo, billingRuleRepo)
	parkingLotHandler := handler.NewParkingLotHandler(parkingLotService)
	gateRepo := impl.NewGateRepo(db)
	deviceRepo := impl.NewDeviceRepo(db)
	gateService := impl2.NewGateService(gateRepo, parkingLotRepo, deviceRepo)
	gateHandler := handler.NewGateHandler(gateService, parkingLotService)
	deviceService := impl2.NewDeviceService(deviceRepo, tenantRepo, parkingLotRepo, gateRepo)
	deviceControlLogRepo := impl.NewDeviceControlLogRepo(db)
	deviceControlService := impl2.NewDeviceControlService(deviceRepo, deviceControlLogRepo)
	deviceHandler := handler.NewDeviceHandler(deviceService, deviceControlService)
	billingRuleService := impl2.NewBillingRuleService(billingRuleRepo, parkingLotRepo, auditLogRepo)
	billingRuleHandler := handler.NewBillingRuleHandler(billingRuleService)
	routerRouter := router.NewRouter(engine, jwtManager, authHandler, tenantHandler, userHandler, parkingLotHandler, gateHandler, deviceHandler, billingRuleHandler)
	return routerRouter, nil
}
