// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/parkhub/api/internal/config"
	"github.com/parkhub/api/internal/handler"
	"github.com/parkhub/api/internal/repository/impl"
	"github.com/parkhub/api/internal/router"
	impl2 "github.com/parkhub/api/internal/service/impl"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeApp wires all dependencies and returns a configured Router.
// Call r.Setup() then r.GetEngine() to start serving.
func InitializeApp(cfg *config.Config, db *gorm.DB) (*router.Router, error) {
	engine := NewGinEngine(cfg)
	jwtManager := NewJWTManager(cfg)
	userRepo := impl.NewUserRepo(db)
	tenantRepo := impl.NewTenantRepo(db)
	refreshTokenRepo := impl.NewRefreshTokenRepo(db)
	smsCodeRepo := impl.NewSmsCodeRepo(db)
	authService := impl2.NewAuthService(userRepo, tenantRepo, refreshTokenRepo, smsCodeRepo, jwtManager)
	authHandler := handler.NewAuthHandler(authService)
	routerRouter := router.NewRouter(engine, jwtManager, authHandler)
	return routerRouter, nil
}
